global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'dcb-benchmark'
    static_configs:
      - targets: ['benchmark:8080']
        labels:
          instance: 'todo-bench'
